id: I2D0E0A3F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:28:31+00:00'
last_modified: '2022-06-07T16:58:33.738348+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16586
  title: བོད་ཀྱི་དབུ་མེད་ཡི་གེའི་གཟུགས་ཆེ་ཆུང་གི་མ་ཕྱི་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9A24:
      image_group_id: I2PD18747
      title: ''
      total_pages: 86
      order: 1
      base_file: 9A24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
