id: P003009
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16586
  title: བོད་ཀྱི་དབུ་མེད་ཡི་གེའི་གཟུགས་ཆེ་ཆུང་གི་མ་ཕྱི་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  volumes:
    82ba8cdfce134f2f9405baf801224a64:
      image_group_id: I2PD18747
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
